require('dotenv').config();
const fs=require('fs'),path=require('path');
const express=require('express');
const Database=require('better-sqlite3');
const {Client,GatewayIntentBits,EmbedBuilder,REST,Routes,SlashCommandBuilder,PermissionFlagsBits,ChannelType}=require('discord.js');
const TOKEN=process.env.DISCORD_TOKEN,CLIENT_ID=process.env.CLIENT_ID,GUILD_ID=process.env.GUILD_ID;
const SECRET=process.env.ALERT_API_SECRET||'',PORT=Number(process.env.PORT||3000),RESET=Number(process.env.RESET_INTERVAL_SECONDS||300);
if(!TOKEN||!CLIENT_ID){console.error('Missing DISCORD_TOKEN or CLIENT_ID');process.exit(1)}
fs.mkdirSync(path.join(process.cwd(),'data'),{recursive:true});
const db=new Database(path.join(process.cwd(),'data','bot.sqlite'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS config(id INTEGER PRIMARY KEY CHECK(id=1),reset_channel TEXT,event_channel TEXT,admin_channel TEXT,rare_channel TEXT,enabled INTEGER DEFAULT 1,last_reset_ms INTEGER);CREATE TABLE IF NOT EXISTS alerts(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,title TEXT,description TEXT,payload TEXT,created_at INTEGER);`);
db.prepare('INSERT OR IGNORE INTO config(id,enabled,last_reset_ms) VALUES(1,1,?)').run(Date.now());
const cfg=()=>db.prepare('SELECT * FROM config WHERE id=1').get();
const save=db.prepare('UPDATE config SET reset_channel=COALESCE(?,reset_channel),event_channel=COALESCE(?,event_channel),admin_channel=COALESCE(?,admin_channel),rare_channel=COALESCE(?,rare_channel) WHERE id=1');
const log=db.prepare('INSERT INTO alerts(type,title,description,payload,created_at) VALUES(?,?,?,?,?)');
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const commands=[
new SlashCommandBuilder().setName('setup').setDescription('Configure alert channels').addChannelOption(o=>o.setName('reset').setDescription('Reset alerts').addChannelTypes(ChannelType.GuildText)).addChannelOption(o=>o.setName('events').setDescription('Event alerts').addChannelTypes(ChannelType.GuildText)).addChannelOption(o=>o.setName('admin').setDescription('Admin-abuse alerts').addChannelTypes(ChannelType.GuildText)).addChannelOption(o=>o.setName('rare').setDescription('Rare egg alerts').addChannelTypes(ChannelType.GuildText)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
new SlashCommandBuilder().setName('status').setDescription('Show monitor status'),new SlashCommandBuilder().setName('nextreset').setDescription('Show estimated next reset'),new SlashCommandBuilder().setName('config').setDescription('Show configuration'),new SlashCommandBuilder().setName('history').setDescription('Show recent alert history').addIntegerOption(o=>o.setName('count').setDescription('1-20').setMinValue(1).setMaxValue(20)),
new SlashCommandBuilder().setName('event').setDescription('Publish event alert').addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Description').setRequired(true)),
new SlashCommandBuilder().setName('adminabuse').setDescription('Publish admin-abuse alert').addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Description').setRequired(true)),
new SlashCommandBuilder().setName('rare').setDescription('Publish rare egg alert').addStringOption(o=>o.setName('egg').setDescription('Egg').setRequired(true)).addStringOption(o=>o.setName('rarity').setDescription('Rarity').setRequired(true)).addStringOption(o=>o.setName('server').setDescription('Server ID'))];
function typeChannel(t){const c=cfg();return {reset:c.reset_channel,event:c.event_channel,admin_abuse:c.admin_channel,rare_egg:c.rare_channel}[t]}
function color(t){return {reset:0x3498db,event:0x9b59b6,admin_abuse:0xe74c3c,rare_egg:0xf1c40f}[t]||0x5865f2}
async function publish({type,title,description='',fields=[],source='unknown'}){log.run(type,title,description,JSON.stringify({fields,source}),Date.now());const id=typeChannel(type);if(!id)return {sent:false,reason:'channel_not_configured'};const ch=await client.channels.fetch(id).catch(()=>null);if(!ch?.isTextBased())return {sent:false,reason:'channel_unavailable'};const e=new EmbedBuilder().setTitle(title).setDescription(description).setColor(color(type)).setTimestamp();if(fields.length)e.addFields(fields);await ch.send({embeds:[e]});return {sent:true}}
function fmt(s){s=Math.max(0,Math.floor(s));return `${Math.floor(s/60)}m ${String(s%60).padStart(2,'0')}s`}
const app=express();app.use(express.json({limit:'32kb'}));
app.get('/health',(_q,r)=>r.json({ok:true,botReady:client.isReady(),game:'Steal An Egg',resetIntervalSeconds:RESET}));
app.post('/ingest',async(req,res)=>{if(!SECRET||req.get('x-alert-secret')!==SECRET)return res.status(401).json({error:'Unauthorized'});const b=req.body||{},t=b.type;if(!['reset','event','admin_abuse','rare_egg'].includes(t))return res.status(400).json({error:'Invalid type'});let title=String(b.title||''),description=String(b.description||'');const fields=[];if(t==='rare_egg'){title||='🥚 Rare Egg Spawn';if(b.egg)fields.push({name:'Egg',value:String(b.egg),inline:true});if(b.rarity)fields.push({name:'Rarity',value:String(b.rarity),inline:true});if(b.server)fields.push({name:'Server',value:String(b.server),inline:true})}else if(t==='admin_abuse')title||='🚨 Admin Abuse Detected';else if(t==='reset')title||='🥚 Egg Reset';else title||='📢 Game Event';const result=await publish({type:t,title,description,fields,source:'ingest'});if(t==='reset')db.prepare('UPDATE config SET last_reset_ms=? WHERE id=1').run(Date.now());res.json({ok:true,result})});
app.listen(PORT,()=>console.log('HTTP ingest server on port '+PORT));
client.once('ready',async()=>{console.log('Logged in as '+client.user.tag);const rest=new REST({version:'10'}).setToken(TOKEN);const body=commands.map(x=>x.toJSON());if(GUILD_ID)await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body});else await rest.put(Routes.applicationCommands(CLIENT_ID),{body});setInterval(async()=>{const c=cfg();if(!c.enabled)return;const last=Number(c.last_reset_ms||Date.now());if(Date.now()-last>=RESET*1000){db.prepare('UPDATE config SET last_reset_ms=? WHERE id=1').run(Date.now());await publish({type:'reset',title:'🥚 Egg Reset',description:'The estimated reset timer reached zero.',fields:[{name:'Next estimate',value:`~${Math.round(RESET/60)} minutes`,inline:true},{name:'Source',value:'Timer estimate',inline:true}],source:'timer'}).catch(console.error)}},5000)});
client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;try{
if(i.commandName==='setup'){save.run(i.options.getChannel('reset')?.id??null,i.options.getChannel('events')?.id??null,i.options.getChannel('admin')?.id??null,i.options.getChannel('rare')?.id??null);await i.reply({content:'Channels updated. Use /config to verify.',ephemeral:true});return}
if(i.commandName==='status'){const c=cfg(),rem=RESET-(Date.now()-Number(c.last_reset_ms||Date.now()))/1000;await i.reply({embeds:[new EmbedBuilder().setTitle('🥚 Steal An Egg Monitor').setColor(0x2ecc71).addFields({name:'Bot',value:'Online',inline:true},{name:'Timer',value:'Estimated',inline:true},{name:'Next reset',value:fmt(rem),inline:true},{name:'Real-time spawns',value:'Requires an observation source',inline:false}).setFooter({text:'Timer alerts are estimates.'})]});return}
if(i.commandName==='nextreset'){const c=cfg(),rem=RESET-(Date.now()-Number(c.last_reset_ms||Date.now()))/1000;await i.reply(`🥚 Estimated next reset: **${fmt(rem)}**`);return}
if(i.commandName==='config'){const c=cfg();await i.reply({content:`Reset: ${c.reset_channel?`<#${c.reset_channel}>`:'not set'}\nEvents: ${c.event_channel?`<#${c.event_channel}>`:'not set'}\nAdmin abuse: ${c.admin_channel?`<#${c.admin_channel}>`:'not set'}\nRare eggs: ${c.rare_channel?`<#${c.rare_channel}>`:'not set'}`,ephemeral:true});return}
if(i.commandName==='history'){const n=i.options.getInteger('count')||10;const rows=db.prepare('SELECT * FROM alerts ORDER BY id DESC LIMIT ?').all(n);await i.reply({content:rows.length?rows.map(r=>`#${r.id} **${r.type}** — ${r.title} — <t:${Math.floor(r.created_at/1000)}:R>`).join('\n'):'No alerts yet.',ephemeral:true});return}
if(i.commandName==='event'){await publish({type:'event',title:i.options.getString('title',true),description:i.options.getString('description',true),source:'discord'});await i.reply({content:'Event alert published.',ephemeral:true});return}
if(i.commandName==='adminabuse'){await publish({type:'admin_abuse',title:i.options.getString('title',true),description:i.options.getString('description',true),source:'discord'});await i.reply({content:'Admin-abuse alert published.',ephemeral:true});return}
if(i.commandName==='rare'){const egg=i.options.getString('egg',true),rarity=i.options.getString('rarity',true),server=i.options.getString('server');await publish({type:'rare_egg',title:'🥚 Rare Egg Spawn',description:'A rare egg alert was published.',fields:[{name:'Egg',value:egg,inline:true},{name:'Rarity',value:rarity,inline:true},...(server?[{name:'Server',value:server,inline:true}]:[])],source:'discord'});await i.reply({content:'Rare egg alert published.',ephemeral:true})}
}catch(e){console.error(e);if(!i.replied)await i.reply({content:'Error. Check the bot console.',ephemeral:true})}});
client.login(TOKEN);
  
